trigger: ["master"]
pr: ["master"]

jobs:
- template: ci/azure-pipelines/job-rust-lint.yml
  parameters:
    name: rust-lint
    rust_version: stable

- template: ci/azure-pipelines/job-rust-check.yml
  parameters:
    name: rust-check-stable
    rust_version: stable

- template: ci/azure-pipelines/job-rust-check.yml
  parameters:
    name: rust-check-nightly
    rust_version: nightly

- template: ci/azure-pipelines/job-rust-check.yml
  parameters:
    name: rust-check-minver
    rust_version: 1.32.0

- template: ci/azure-pipelines/job-rust-test.yml
  parameters:
    name: rust-test-stable
    rust_version: stable
