trigger: ["master"]
pr: ["master"]

jobs:
- template: ci/azure-pipelines/job-rust-lint.yml
  parameters:
    name: rust_lint
    rust_version: stable

- template: ci/azure-pipelines/job-rust-check.yml
  parameters:
    name: rust_check_stable
    rust_version: stable

- template: ci/azure-pipelines/job-rust-check.yml
  parameters:
    name: rust_check_nightly
    rust_version: nightly

- template: ci/azure-pipelines/job-rust-check.yml
  parameters:
    name: rust_check_minver
    rust_version: 1.32.0

- template: ci/azure-pipelines/job-rust-test.yml
  parameters:
    name: rust_test_stable
    rust_version: stable
