trigger: ["master"]
pr: ["master"]

jobs:
- template: ci/azure-pipelines/job-rust-lint.yml
  parameters:
    name: rust-lint
    rust_version: stable

- template: ci/azure-pipelines/job-rust-version.yml
  parameters:
    name: rust-version
    rust_version: 1.33.0
