trigger: ["master"]
pr: ["master"]

resources:
  containers:
  - container: postgres
    image: postgres:10
    ports:
    - 5432:5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

stages:
- template: ci/stages/build.yml
- template: ci/stages/release.yml
