trigger: ["master"]
pr: ["master"]

resources:
  containers:
  - container: postgres
    image: postgres:10
    ports:
    - 5432:5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

stages:
- stage: lint
  displayName: Lint
  dependsOn: []
  jobs:
  - template: ci/job-cargo-lint.yml
    parameters:
      name: lint_rust
      label: Rust
      toolchain: target

- stage: build
  displayName: Build
  dependsOn: []
  jobs:
  - template: ci/job-cargo-build.yml
    parameters:
      name: build_x86_64_unknown_linux_gnu
      label: x86_64-unknown-linux-gnu
      target: x86_64-unknown-linux-gnu
      toolchain: target
      image: ubuntu-16.04

  - template: ci/job-cargo-build.yml
    parameters:
      name: build_x86_64_apple_darwin
      label: x86_64-apple-darwin
      target: x86_64-apple-darwin
      toolchain: target
      image: macos-10.13

  - template: ci/job-cross-build.yml
    parameters:
      name: build_x86_64_unknown_linux_musl
      label: x86_64-unknown-linux-musl
      target: x86_64-unknown-linux-musl
      toolchain: target
      image: ubuntu-16.04

- stage: test
  displayName: Test
  dependsOn: []
  jobs:
  - template: ci/job-cargo-test.yml
    parameters:
      name: test_rust
      label: Rust
      toolchain: target

- stage: release
  displayName: Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
  - lint
  - build
  - test
  jobs:
  - template: ci/job-docker-push.yml
    parameters:
      name: release_docker_push
      label: Docker Push
      images:
      - alpine

  - template: ci/job-helm-package.yml
    parameters:
      name: release_helm_package
      label: Helm Package
      charts:
      - brace
