[package]
name = "brace"
version = "0.1.0"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
description = "A content management system built with the rust programming language."
edition = "2018"
homepage = "https://github.com/brace-rs/brace"
repository = "https://github.com/brace-rs/brace"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
actix = "0.7"
actix-web = "0.7"
clap = "2.32"
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
