jobs:
- job: ${{ parameters.name }}
  displayName: Rust test ${{ parameters.rust_version }}
  pool:
    vmImage: ubuntu-16.04
  services:
    postgres: postgres
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust_version }}

  - script: cargo test --all -- --test-threads=1
    displayName: Run cargo test
