parameters:
  version: stable
  targets: []

jobs:
- job: ${{ parameters.name }}
  displayName: Cross Build
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      version: ${{ parameters.version }}

  - template: ../steps/install-cross.yml

  - ${{ each target in parameters.targets }}:
    - script: cross build --release --target ${{ target }} --verbose
      displayName: Release ${{ target }}

    - task: ArchiveFiles@2
      displayName: Create artifact ${{ target }}.tar.gz
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/target/${{ target }}/release/brace'
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.ArtifactStagingDirectory)/brace-${{ target }}.tar.gz'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact ${{ target }}.tar.gz
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/brace-${{ target }}.tar.gz'
        artifactName: 'brace-${{ target }}'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
