parameters:
  name: test
  label: Test
  toolchain: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  services:
    postgres: postgres
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - script: cargo test --all -- --test-threads=1
    displayName: Test
