parameters:
  version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: Rust Check (${{ parameters.version }})
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      version: ${{ parameters.version }}

  - script: cargo check --all
    displayName: Run cargo check
