parameters:
  name: cross_build
  label: Cross Build
  toolchain: stable
  target: x86_64-unknown-linux-musl

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - template: ../steps/install-cross.yml

  - script: cross build --release --target ${{ parameters.target }} --verbose
    displayName: Build

  - task: ArchiveFiles@2
    displayName: Create artifact
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/target/${{ parameters.target }}/release/brace'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'
      artifactName: 'brace-${{ parameters.target }}'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
