parameters:
  name: build
  label: Build
  toolchain: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}
      components:
      - rustfmt
      - clippy

  - script: cargo check --all
    displayName: Check

  - script: cargo fmt --all -- --check
    displayName: Rustfmt

  - script: cargo build --all
    displayName: Build

  - script: cargo clippy --all -- -D warnings
    displayName: Clippy
