parameters:
  version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: Cross Build (${{ parameters.target }})
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      version: ${{ parameters.version }}

  - template: ../steps/install-cross.yml

  - script: cross build --release --target ${{ parameters.target }} --verbose
    displayName: Compile release

  - task: ArchiveFiles@2
    displayName: Create artifact
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/target/${{ parameters.target }}/release/brace'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'
      artifactName: 'brace-${{ parameters.target }}'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
