parameters:
  version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: Rust Test (${{ parameters.version }})
  pool:
    vmImage: ubuntu-16.04
  services:
    postgres: postgres
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      version: ${{ parameters.version }}

  - script: cargo test --all -- --test-threads=1
    displayName: Run cargo test
