stages:
- stage: build
  displayName: Build
  jobs:
  - template: ../jobs/rust-check.yml
    parameters:
      name: rust_check_stable
      version: stable

  - template: ../jobs/rust-check.yml
    parameters:
      name: rust_check_nightly
      version: nightly

  - template: ../jobs/rust-check.yml
    parameters:
      name: rust_check_minimum
      version: 1.33.0

  - template: ../jobs/rust-cross-build.yml
    parameters:
      name: build
      version: stable
      targets:
      - x86_64-unknown-linux-musl
