stages:
- stage: build
  displayName: Build
  jobs:
  - template: ../jobs/rust-build.yml
    parameters:
      name: build_stable
      label: Build (stable)
      toolchain: stable

  - template: ../jobs/rust-check.yml
    parameters:
      name: check_nightly
      label: Check (nightly)
      toolchain: nightly

  - template: ../jobs/rust-check.yml
    parameters:
      name: check_minimum
      label: Check (minimum)
      toolchain: 1.33.0

  - template: ../jobs/rust-cross-build.yml
    parameters:
      name: cross_build_x86_64_unknown_linux_musl
      label: Cross Build (x86_64-unknown-linux-musl)
      target: x86_64-unknown-linux-musl
      toolchain: stable
