stages:
- stage: release
  displayName: Release
  jobs:
  - template: ../jobs/docker-push.yml
    parameters:
      name: docker_push
      images:
      - alpine

  - template: ../jobs/helm-chart.yml
    parameters:
      name: helm_chart
      charts:
      - brace
