steps:
- script: |
    set -eou
    D=$(mktemp -d)
    git clone https://github.com/rust-embedded/cross.git "$D"
    git reset --hard 718a19cd68fb09428532d1317515fe7303692b47
    cd "$D"
    curl -O -L "https://gist.githubusercontent.com/nickbabcock/c7bdc8e5974ed9956abf46ffd7dc13ff/raw/e211bc17ea88e505003ad763fac7060b4ac1d8d0/patch"
    git apply patch
    cargo install --path .
    rm -rf "$D"
  displayName: Install cross
