jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: HelmInstaller@0
    displayName: Install helm
    inputs:
      helmVersion: 2.9.1
      checkLatestHelmVersion: true
      installKubectl: true
      kubectlVersion: 1.8.9
      checkLatestKubectl: true

  - ${{ each chart in parameters.charts }}:
    - task: DeleteFiles@1
      displayName: Clean
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        contents: '**'

    - task: HelmDeploy@0
      displayName: Package ${{ chart }}
      inputs:
        command: package
        chartPath: charts/${{ chart }}
        destination: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish ${{ chart }}
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'chart-${{ chart }}'
