jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: step-install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}
      components:
      - rustfmt
      - clippy

  - script: cargo fmt --all -- --check
    displayName: Rustfmt

  - script: cargo clippy --all -- -D warnings
    displayName: Clippy
