jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: step-install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - script: cargo check --all
    displayName: Check
