jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: step-install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - template: step-install-cross.yml

  - script: cross build --release --target ${{ parameters.target }}
    displayName: Build

  - task: ArchiveFiles@2
    displayName: Archive
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/target/${{ parameters.target }}/release/brace'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'

  - task: PublishBuildArtifacts@1
    displayName: Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'
      artifactName: 'brace-${{ parameters.target }}'
