jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - template: ../step-install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - script: cargo build --release --target ${{ parameters.target }}
    displayName: Build

  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/target/${{ parameters.target }}/release/brace'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'

  - task: PublishBuildArtifacts@1
    displayName: Publish
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/brace-${{ parameters.target }}.tar.gz'
      artifactName: 'brace-${{ parameters.target }}'
