[manifest]
name = "default"
label = "Default"
description = "The resource manifest for the default theme."

[[libraries]]
name = "theme"
resources = [
  "theme.css",
  "font",
]

[[resources]]
name = "theme.css"
type = "css"
location = "css/theme.css"

[[resources]]
name = "font"
type = "css"
location = "https://fonts.googleapis.com/css?family=Roboto:400,500"

[[templates]]
name = "resource"
type = "tera"
path = "templates/resource.html"

[[templates]]
name = "index"
type = "tera"
path = "templates/index.html"

[[templates]]
name = "themes"
type = "tera"
path = "templates/themes.html"

[[templates]]
name = "page"
type = "tera"
path = "templates/page.html"

[[templates]]
name = "page-list"
type = "tera"
path = "templates/page-list.html"

[[templates]]
name = "page-form"
type = "tera"
path = "templates/page-form.html"

[[templates]]
name = "page-delete-form"
type = "tera"
path = "templates/page-delete-form.html"
