[manifest]
name = "default"
label = "Default"
description = "The resource manifest for the default theme."

[[libraries]]
name = "theme"
resources = [
  "theme.css",
  "font",
]

[[resources]]
name = "theme.css"
type = "css"
location = "css/theme.css"

[[resources]]
name = "form.css"
type = "css"
location = "css/form.css"

[[resources]]
name = "font"
type = "css"
location = "https://fonts.googleapis.com/css?family=Roboto:400,500"

[[templates]]
name = "resource"
type = "tera"
path = "templates/resource.html"

[[templates]]
name = "index"
type = "tera"
path = "templates/index.html"

[[templates]]
name = "themes"
type = "tera"
path = "templates/themes.html"

[[templates]]
name = "layout"
type = "tera"
path = "templates/layout.html"

[[templates]]
name = "page"
type = "tera"
path = "templates/page/page.html"

[[templates]]
name = "page-list"
type = "tera"
path = "templates/page/page-list.html"

[[templates]]
name = "page-form"
type = "tera"
path = "templates/page/page-form.html"

[[templates]]
name = "page-delete-form"
type = "tera"
path = "templates/page/page-delete-form.html"

[[templates]]
name = "user"
type = "tera"
path = "templates/user/user.html"

[[templates]]
name = "user-list"
type = "tera"
path = "templates/user/user-list.html"

[[templates]]
name = "user-form"
type = "tera"
path = "templates/user/user-form.html"

[[templates]]
name = "user-delete-form"
type = "tera"
path = "templates/user/user-delete-form.html"

[[templates]]
name = "login-form"
type = "tera"
path = "templates/auth/login-form.html"

[[templates]]
name = "logout-form"
type = "tera"
path = "templates/auth/logout-form.html"

[[templates]]
name = "form"
type = "tera"
path = "templates/form/form.html"

[[templates]]
name = "field"
type = "tera"
path = "templates/form/field/field.html"

[[templates]]
name = "field--datetime"
type = "tera"
path = "templates/form/field/field--datetime.html"

[[templates]]
name = "field--hidden"
type = "tera"
path = "templates/form/field/field--hidden.html"

[[templates]]
name = "field--select"
type = "tera"
path = "templates/form/field/field--select.html"

[[templates]]
name = "field--text"
type = "tera"
path = "templates/form/field/field--text.html"

[[templates]]
name = "field--textarea"
type = "tera"
path = "templates/form/field/field--textarea.html"
