[theme]
name = "default"
label = "Default"
description = "The default theme for all new sites."

[[library]]
name = "theme"

[[library.asset]]
name = "theme.css"
type = "css"
location = "css/theme.css"

[[library.asset]]
name = "font"
type = "css"
location = "https://fonts.googleapis.com/css?family=Roboto:400,500"

[[template]]
name = "asset"
type = "tera"
path = "templates/asset.html"

[[template]]
name = "index"
type = "tera"
path = "templates/index.html"

[[template]]
name = "themes"
type = "tera"
path = "templates/themes.html"
