[theme]
name = "default"
label = "Default"
description = "The default theme for all new sites."

[templates]
index = { name = "index", path = "templates/index.html" }
themes = { name = "themes", path = "templates/themes.html" }
